src/main/java/com/senzing/api/server/services/EntityGraphServices.java, src/main/java/com/senzing/api/server/services/ServicesUtil.java
Null pointers
Wrong query param annotation
Incorrect conditionals
Redundant initializers
Unused values
Used StringBuilder in one place instead of frequent String +=.
=> Graph API bug fixes.

pom.xml, src/main/java/com/senzing/api/server/SzApiServer.java
Upgrading to version 2.9.8 should address the security issue in Jackson libraries.
=> Upgraded jackson JSON libraries to v2.9.8 from v2.8.10 due to security bug in Jackson

src/main/java/com/senzing/api/model/SzAttributeSearchResponse.java, src/main/java/com/senzing/api/model/SzAttributeTypeResponse.java, src/main/java/com/senzing/api/model/SzAttributeTypesResponse.java, src/main/java/com/senzing/api/model/SzBasicResponse.java, src/main/java/com/senzing/api/model/SzDataSourcesResponse.java, src/main/java/com/senzing/api/model/SzEntityNetworkResponse.java, src/main/java/com/senzing/api/model/SzEntityPathResponse.java, src/main/java/com/senzing/api/model/SzEntityResponse.java, src/main/java/com/senzing/api/model/SzErrorResponse.java, src/main/java/com/senzing/api/model/SzLicenseResponse.java, src/main/java/com/senzing/api/model/SzLinks.java, src/main/java/com/senzing/api/model/SzLoadRecordResponse.java, src/main/java/com/senzing/api/model/SzRecordResponse.java, src/main/java/com/senzing/api/model/SzResponseWithRawData.java, src/main/java/com/senzing/api/server/LifeCycleListener.java, src/main/java/com/senzing/api/server/SzApiServer.java, src/main/java/com/senzing/api/server/services/AdminServices.java, src/main/java/com/senzing/api/server/services/ConfigServices.java, src/main/java/com/senzing/api/server/services/EntityDataServices.java, src/main/java/com/senzing/api/server/services/EntityGraphServices.java, src/main/java/com/senzing/api/server/services/ServicesUtil.java
- Modified "model" classes to accept "UriInfo" objects in addition to "String" self links.  The UriInfo object is used to extract the self link from the associated request.
- Modified the "services" classes to inject the "UriInfo" using the "@Context" annotation so the actual request URL can be used in the self link rather than the constructed ones.
- Removed unused methods from SzApiServer (makeLink())
- Fixed LifeCycleListener to output the host address instead of the InetAddr object
=> Fixed Self Links

README.md, app-scripts/README.md, app-scripts/run-rest-api-server.bat, app-scripts/run-rest-api-server.sh
I added the instructions of how to use the Senzing REST API Server along with the Senzing App for development purposes using the provided scripts.
This works with version 1.5 patch 1 (due out in mid February).  However, we can get an early version to anybody doing the beta program who needs it before next Friday.
I would like to update all other repository README's that provide instructions on using the internal paths of the app to leverage the Senzing app projects with the Senzing REST API Server, to instead reference this or just reference the primary README file of the Senzing REST API Server, which now references this.
We should not be creating dependencies on internal paths that may change, so this allows us to control that by minimizing our exposure.
=> Issue 15.caceres.app scripts

src/main/java/com/senzing/api/model/SzRecordId.java, src/main/java/com/senzing/api/server/services/EntityGraphServices.java, src/main/java/com/senzing/api/server/services/ServicesUtil.java
Modified EntityGraphServices to accept delimited encoding for SzRecordId.
Also modified EntityGraphServices so "entity-paths" and "entity-networks" return 400 errors when entities or records are not found.
=> Added delimited encoding for SzRecordId and proper error checking for entity-paths/entity-networks

src/main/java/com/senzing/api/model/SzEntityIdentifier.java, src/main/java/com/senzing/api/model/SzEntityIdentifiers.java, src/main/java/com/senzing/api/model/SzRecordId.java, src/main/java/com/senzing/api/server/services/EntityGraphServices.java, src/main/java/com/senzing/api/server/services/ServicesUtil.java
Added the following parameters:
- entity-paths: "avoidEntities" in addition to "x" parameter -- if both are specified then entity identifiers are merged.
- entity-networks: "entities" in addition to "e" parameter -- if both are specified then entity identifiers are merged.
In both cases all entity identifiers must be SzRecordId or SzEntityId -- you cannot mix and match.
=> Added entities and avoidEntities parameters to specify multiple entity identifiers in a single parameter as a comma-separated list or JSON array

src/main/java/com/senzing/api/server/services/EntityGraphServices.java, src/main/java/com/senzing/api/server/services/ServicesUtil.java
Found and fixed error reporting issue that made it possible to see the source of the NullPointerException.
Then found and fixed the NullPointerException (specifically caused by order-of-operation issue by misplaced parentheses).
=> Fixed NullPointerException and error reporting of it for /entity-networks

src/main/java/com/senzing/api/model/SzBaseRelatedEntity.java, src/main/java/com/senzing/api/model/SzEntityRecord.java, src/main/java/com/senzing/api/model/SzMatchedRecord.java, src/main/java/com/senzing/api/model/SzResolvedEntity.java, src/main/java/com/senzing/api/server/services/EntityDataServices.java
This resolves Issue #51 .
This is solved by creating SzMatchedRecord which extends SzEntityRecord to add the needed fields.
This is required because the "GET /data-sources/{dataSourceCode}/records/{recordId}" end-point uses "getRecord()" and does not get these fields returned (nor do they make sense for that endpoint). So SzEntityRecord still exists to service that endpoint.
SzResolvedEntity is modified to maintain an array of SzMatchedRecord instead which adds the needed fields for the "GET /entities/{entityId}" endpoint as well as others.
EntityDataServices required update as well to work with lists of SzMatchedRecord.  
Finally, I factored out the functionality for extracting the MATCH_SCORE from native Senzing JSON in SzBaseRelatedEntity into a public static function on the same class …
=> Added SzMatchedRecord which extends SzEntityRecord to resolve issue 51

pom.xml, src/main/java/com/senzing/api/server/G2EngineRetryHandler.java, src/main/java/com/senzing/api/server/SzApiServer.java
- Added error handling for bad result from G2ConfigMgr.initV2() in the getConfigType() function
- Added additional methods to the explicitly unsupported list to avoid warnings on startup if building with version 1.11.x pre-release of g2.jar
- Increased version number in pom.xml to 1.7.3
=> Error handling for configMgr.initV2() in getConfigType() + misc other improvements

CHANGELOG.md, pom.xml, src/main/java/com/senzing/cmdline/CommandLineUtilities.java, src/main/java/com/senzing/configmgr/ConfigurationManager.java, src/main/java/com/senzing/repomgr/RepositoryManager.java, src/main/java/com/senzing/util/LoggingUtilities.java, src/test/java/com/senzing/api/GenerateTestJVMScript.java, src/test/java/com/senzing/api/services/AbstractServiceTest.java, src/test/java/com/senzing/api/services/AdminServicesTest.java
- Added tracking of last exception logged to reduce repetititve output when command line options are invalid.
- Fixed auto tests when building with version 1.11.1 or later of native Senzing libs
- Updated Changelog and updated to version 1.7.4.
=> Fixed auto tests on 1.11.1 and reduced repetitive output when command line args are invalid

CHANGELOG.md, pom.xml, src/main/java/com/senzing/api/model/SzVersionInfo.java, src/test/java/com/senzing/api/services/AdminServicesTest.java
Modified SzVersionInfo so that `configCompatabilityVersion` is represented as a string instead of an integer so that semantic versioning is possible.
=> Updated SzVersionInfo configCompatibilityVersion to be a string

CHANGELOG.md, pom.xml, src/main/java/com/senzing/api/model/SzVersionInfo.java, src/main/java/com/senzing/repomgr/RepositoryManager.java, src/test/java/com/senzing/api/services/AbstractServiceTest.java, src/test/java/com/senzing/api/services/AdminServicesTest.java, src/test/java/com/senzing/api/services/AutoReinitializeTest.java, src/test/java/com/senzing/api/services/ConfigServicesTest.java, src/test/java/com/senzing/api/services/EntityDataReadServicesTest.java, src/test/java/com/senzing/api/services/EntityDataWriteServicesTest.java, src/test/java/com/senzing/api/services/EntityGraphServicesTest.java, src/test/java/com/senzing/api/services/ExplicitConfigIdTest.java, src/test/java/com/senzing/api/services/ReadOnlyEntityDataWriteServicesTest.java
- Updated dependency on FasterBind's Jackson library to version 2.9.10 to 
address security vulnerabilities.
- Added missing G2ConfigMgr.destroy() call in SzApiServer during shutdown
- Updated repository manager code used for JUnit tests to check for errors
when initializing the configuration manager and when creating the standard
configuration.
- Changes to Unit Tests:
- Updated unit tests to preserve repos if any tests associated with that 
repo failed.
- Updated location of unit test entity repos to live in the 
`./target/test-repos` directory during a Maven build and modified the 
repo directory names to be based off the associated unit test name.
- Updated the module name used for Senzing initialization in auto tests to 
match the current auto test for post-failure diagnostic …
=> Address Security Vulnerabilities, fix SzApiServer shutdown, improved error checking and unit tests

pom.xml
Changed dependency range to:
<version>[1.10.0-SNAPSHOT,2.0.0-SNAPSHOT)</version>
=> Corrected dependency range for g2.jar

src/test/java/com/senzing/api/services/AbstractServiceTest.java
Fixed it so tests skip again if the G2 native libraries are not installed.
=> Fix for tests failing instead of skipping if G2 native libraries are not installed

CHANGELOG.md, src/main/java/com/senzing/api/BuildInfo.java, src/main/java/com/senzing/api/server/SzApiServer.java, src/main/java/com/senzing/cmdline/CommandLineUtilities.java
Modified CommandLineUtilities to do a "setLastLoggedAndThrow()" to throw an exception if a primary option is not provided.
Modified SzApiServer to NOT double-log exceptions that were already logged.
Updated CHANGELOG.md
=> Minor changes to error handling on bad command line & changelog update

CHANGELOG.md, Dockerfile, pom.xml, src/main/java/com/senzing/nativeapi/InstallLocations.java, src/test/java/com/senzing/io/TemporaryDataCacheTest.java
- Supports environment variables for Senzing install locations
- SENZING_G2_DIR
- SENZING_DATA_DIR
- SENZING_ETC_DIR
- Supports default to `/opt/senzing/data` as the support directory if the versioned sub-directory is not found and the base directory contains expected files.
- Shortens the test time for TemporaryDataCacheTest 
- Updated Dockerfile for Java 11
=> Updated Install Locations logic, uses environment variables

.github/workflows/cd-daily-cron-test-debian-build.yml
Make the debian build test run every day instead of every 3 hours.
=> Moving test to a daily run

README.md, src/main/java/com/senzing/api/server/SzApiServer.java, src/main/java/com/senzing/api/services/ConfigServices.java
The changes included are not significant enough to release a patch to version 2.5.0 but should be included in the next release and are safe to merge to master:
1) Updated `README.md` with the latest usage message.
2) Fixed Jetty warning complaining about base path ending with a forward slash when not set to `/`.
3) Updated `com.senzing.api.services.ConfigServices` to remove hard-coded references to `SzHttpMethod.PUT` and instead use the `httpMethod` variable that was passed so that when exceptions occur the response has the correct HTTP method in the "meta" section.
4) Updated `com.senzing.api.services.ConfigServices` truncate the config comment to a maximum size of 150 characters to prevent overly large comments which can cause `G2ConfigMgr.addConfig()` to fail on some versions of …
=> Minor updates post 2.5.0 release to fix README and Jetty Warning

CHANGELOG.md, Dockerfile, pom.xml, src/main/java/com/senzing/cmdline/CommandLineUtilities.java
Version 2.7.2 resolves a minor issue in CommandLineUtilities class so repos that extend Senzing API Server and build on it and add new command-line options while still recognizing the environment variables from the Senzing API Server base options as well.
No changes to any runtime functionality -- this only affects repos that leverage the command-line option extension mechanism provided in the code base.
=> Minor changes for version 2.7.2

CHANGELOG.md, Dockerfile, pom.xml, src/main/java/com/senzing/api/model/impl/SzLinksImpl.java, src/main/java/com/senzing/api/server/DebugRequestFilter.java, src/main/java/com/senzing/api/server/SzApiServer.java, src/main/java/com/senzing/api/server/SzApiServerOption.java, src/main/java/com/senzing/api/services/BulkDataSupport.java, src/main/java/com/senzing/api/services/BulkDataWebSocket.java, src/main/java/com/senzing/api/websocket/WebSocketFilter.java, src/main/java/com/senzing/cmdline/CommandLineUtilities.java, src/main/java/com/senzing/io/TemporaryDataCache.java, src/main/java/com/senzing/util/LoggingUtilities.java, src/main/resources/com/senzing/api/build-info.properties
- Added --debug command-line option with SENZING_API_SERVER_DEBUG environment variable equivalent to enable API Server debug logging.
- Added debug logging of every incoming request if --debug enabled.
- Added debug logging for bulk-data related operations if --debug enabled.
- Updated build-info.properties so the Maven build timestamp is properly filtered during build and token-replaced.
- Minor bug fix for internal CommandLineUtilities class to process default values for "base" options.  This allows others to extend the Senzing API Server code with new options but still have the default values from the  base options be populated (required for `Senzing/senzing-poc-server`).
=> Version 2.7.3 of API Server

CHANGELOG.md, Dockerfile
Issue number: #260
To improve the attack surface of the Api Server image.
Updated to Debian:11.2-slim which fixed many vulnerabilities and is ~100MB smaller than a Debian:11.2 based image.
In version 2.8.1 Snyk reports that it checked 414 dependencies for known issues and found 240 issues.
In the updated version Snyk reports that it checked 223 dependencies for known issues and found 80 issues.
EDIT:  on 27 Jan 2022 there was a new release of Debian 11.2 and a new vulnerabilities database the version we were using 2 days ago now has 85 issues and the new version has 83.  
Removal of installed but unused packages accounts for many of the dependencies.  Update of the OS brings down the number of issues found.
Below is a list of the 8 Critical and 8 High vulnerabilities that Snyk found.  As …
=> Issue 260.ron.0

CHANGELOG.md, pom.xml
Updates to `pom.xml` to prevent pulling beta `3.0.0` versions of `senzing-sdk-java` and `senzing-commons-java` via the Maven dependency range.
=> Version 2.8.4: Updates to pom.xml to exclude beta 3.x dependencies of Senzing artifacts.

pom.xml
When updating Jersey to version 2.35 and Jackson to 2.13.3, some of the related dependencies also needed their versions
bumped to those latest versions.
=> Version 3.3.0 -- some missed dependency updates

pom.xml
- pom.xml version updated to 3.3.0
- senzing-rest-api-specification 3.2.0 latest release with updated documentation now being used
- updated sqlite-jdbc dependency to version 3.39.2.0
=> Updated pom.xml and to use latest senzing-rest-api-specification

CHANGELOG.md, Dockerfile, pom.xml
Updated dependency on `Senzing/senzing-commons-java` to a minimum version of `3.0.1` to resolve issue with environment variable fallbacks for primary options which typically lack dependencies.
=> V3.3.1 Release: Updated to latest senzing-commons-java to resolve environment variable fallback issue

.github/dependabot.yml
Changed dependabot schedule to `monthly` instead of `daily`.
=> Updated dependabot schedule for standard updates that are not security vulnerabilities

CHANGELOG.md, Dockerfile, pom.xml, src/main/java/com/senzing/api/server/AppLifeCycle.java, src/main/java/com/senzing/api/server/G2EngineRetryHandler.java
- Updated `G2EngineRetryHandler` to retry calls that return engine error codes
that indicate auto-reconnection can cause the call to succeed.
- Added additional logging to `G2EngineRetryHandler` to better log retry 
failures so the original and secondary failure are both logged.
- Removed unused `com.senzing.server.AppLifeCycle` class
- In `pom.xml`,
- Updated `jackson-databind` to 2.13.4.2
=> Version 3.4.4: Adding auto-retry on engine reconnect errors

CHANGELOG.md, Dockerfile, pom.xml
- Reverted `jaxb-impl` version from `4.0.1` to `2.3.1` to prevent warning regarding WADL feature 
- Updated JUnit Jupiter version property to 5.9.1 to match actual version
- Updated Maven shade plugin version
=> Version 3.4.7: Fixed the version updates from dependabot to remove runtime warnings

README.md
For some reason `senzing_api_service_port` was referenced repeatedly.  Not only was this wrong for the port environment variable which should be `senzing_api_server_port`, it was copy/pasted for every other environment variable which did not yet existed in the knowledge base.
This change corrects all those references to use the new environment variable references.
=> Coincides with Knowledge Base Issue #49 Fix -- Correct references to API Server environment variables

CHANGELOG.md, Dockerfile, pom.xml, src/main/java/com/senzing/repomgr/RepositoryManager.java
Version 3.4.12
- Removed `LICENSEFILE` from `g2-init.json` file produced by `RepositoryManager`
- Updated dependency versions to newer releases.
=> Dependabot updates + LICENSEFILE removal from RepositoryManager

CHANGELOG.md, Dockerfile, pom.xml
- Updated `sqlite-jdbc` to version `3.42.0.0`
- Updated Jersey dependencies to version `2.40`
- Updated `icu4j` to version `73.2`
- Updated `sqs` to version `2.20.94`
- Updated `amqp-client` to version `5.18.0`
- Updated `kafka-clients` to version `3.5.0`
=> Version 3.5.5: Updates to dependency versions

CHANGELOG.md, pom.xml, src/main/java/com/senzing/api/services/ServicesSupport.java
- Reverted sqlite-jdbc to 3.42.0.1 because the SQLite team haphazardly removed functionality that has been supported for 16 years.
- Added method to ServicesSupport for creating InternalServerErrorExceptions with a String message rather than a G2Fallible or another Exception
- Updated other dependencies to newer versions to match other Senzing projects
=> Version 3.5.9 Release in support of new POC Server

CHANGELOG.md, Dockerfile, pom.xml
- Updated dependencies:
- Updated `senzing-commons` to version `3.2.0` from version `3.1.4` 
- Updated Jetty dependencies to version `9.4.54.v20240208`
from version `9.4.53.v20231009` 
- Updated Jackson dependencies to version `2.16.1` from version `2.15.3`
- Updated `junit-jupiter` to version `5.10.2` from version `5.10.1`
- Updated `icu4j` to version `74.2` from version `74.1`
- qUpdated `sqs` to version `2.24.12` from version `2.21.40`
- Updated `kafka-clients` to version `3.7.0` from version `3.6.1`
- Updated SLF4J dependencies to version `2.0.12` from version `2.0.9`
- Updated `org.glassfish/javax.annotation` to `jakarta.annotation-api` version `2.1.1`
- Updated Spring dependencies to version `5.3.32` from version `5.3.30`
- Updated `swagger-annotations` to version `2.2.20` from …
=> Version 3.5.10 (Dependency Updates)

.gitignore, CHANGELOG.md, Dockerfile, pom.xml
- Updated `jetty-xxxx` dependencies from version `9.4.54.v20240208` to `9.4.55.v20240627`
- Updated `jersey-xxxx` dependencies from version `2.43` to `2.44`
- Updated `jackson-xxxx` dependencies from version `2.17.1` to `2.17.2`
- Updated Amazon `sqs` from version `2.26.4` to `2.26.27`
- Updated `kafka-clients` dependencies from version `3.7.0` to `3.8.0`
- Updated `junit-jupiter` from version `5.10.2` to `5.10.3`
=> Updated dependencies for version 3.5.14 release

src/test/java/com/senzing/nativeapi/replay/ReplayNativeApiProvider.java
Modified how ReplayNativeApiProvider constructs initialization exception to not mask underlying cause.
=> Modified how ReplayNativeApiProvider constructs initialization exception to not mask underlying cause.
