- src/main/java/com/senzing/api/server/SzApiServer.java
Add an -allowedOrigins command line option.
> Make CORS Access-Control-Allowed-Origins configurable via command line

- pom.xml
Changed acceptable version range of com.senzing.g2 dependency.
> issue-25 Change com.senzing.g2 upper limit to be less than 2.

- README.md
Updated documentation in README.md to indicate that a restart is needed when the config changes.
> Updated docs to reflect the need to restart when the config changes

- README.md
Updated Docs to reflect that any method can fail on config changes.
> Updated docs regarding restart on config-change to describe additional failures

- README.md
ISSUE-36
Configuration section was missing variables.
> issue-36 Added configuration variables

- pom.xml
- src/main/java/com/senzing/api/model/SzAttributeSearchResponse.java
- src/main/java/com/senzing/api/model/SzAttributeSearchResult.java
- src/main/java/com/senzing/api/model/SzAttributeTypeResponse.java
- src/main/java/com/senzing/api/model/SzAttributeTypesResponse.java
- src/main/java/com/senzing/api/model/SzBaseRelatedEntity.java
- src/main/java/com/senzing/api/model/SzBasicResponse.java
- src/main/java/com/senzing/api/model/SzDataSourcesResponse.java
- src/main/java/com/senzing/api/model/SzEntityNetworkResponse.java
- src/main/java/com/senzing/api/model/SzEntityPathResponse.java
- src/main/java/com/senzing/api/model/SzEntityRecord.java
- src/main/java/com/senzing/api/model/SzEntityResponse.java
- src/main/java/com/senzing/api/model/SzErrorResponse.java
- src/main/java/com/senzing/api/model/SzFeatureInclusion.java
- src/main/java/com/senzing/api/model/SzLicenseResponse.java
- src/main/java/com/senzing/api/model/SzLoadRecordResponse.java
- src/main/java/com/senzing/api/model/SzMeta.java
- src/main/java/com/senzing/api/model/SzRecordResponse.java
- src/main/java/com/senzing/api/model/SzRelatedEntity.java
- src/main/java/com/senzing/api/model/SzResolvedEntity.java
- src/main/java/com/senzing/api/model/SzResponseWithRawData.java
- src/main/java/com/senzing/api/server/services/AdminServices.java
- src/main/java/com/senzing/api/server/services/ConfigServices.java
- src/main/java/com/senzing/api/server/services/EntityDataServices.java
- src/main/java/com/senzing/api/server/services/EntityGraphServices.java
- src/main/java/com/senzing/api/server/services/ServicesUtil.java
- src/main/java/com/senzing/util/JsonUtils.java
- src/main/java/com/senzing/util/Timers.java
- src/main/resources/com/senzing/api/build-info.properties
- Added the "forceMinimal" and "featureMode" parameters to entity functions
- Added the "withRelationships" parameter to the entity search
- Added "version" to SzMeta and support for obtaining it from build
- Added "timings" to SzMeta along with Timers object to assist
- Added "attr_[param]" to the /entities as a shortcut for specifying search features
- Refactored all the "services/*" implementations to minimize the work done inside the "executeInThread" blocks to reduce the time the engine thread is reserved.
> Issue 39: Added V2 entity function support, timings in SzMeta, version in SzMeta

- README.md
- app-scripts/README.md
> Updated README files for v1.6.0 API server working with v1.7.x API/App builds

- Dockerfile
- README.md
ISSUE-44
Make documentation match template.
> Issue 44.dockter.1

- .gitignore
- .project
- Dockerfile
- Dockerfile-package
- Makefile
- README.md
- docker-compose.test.yml
- rootfs/app/container-test.sh
- rootfs/app/healthcheck.sh
> issue-44  Preparation for inspectDockerImage testing

- README.md
> issue-44 Fixed URLs

- src/main/java/com/senzing/api/server/SzApiServer.java
This resolves Issue #53 
It modifies SzApiServer.java main() function to create a background thread that will check every six hours if the license is already expired or within 30 days of expiring and output an appropriate message to stderr to warn the user.
Stderr should be easy enough to pickup for anybody building this into a Docker image and should show up in whatever logs are being monitored.
> Added message for when license is already expired or close to expiring

- CHANGELOG.md
- Dockerfile
> issue-57 Pin to version of senzing/senzing-base:1.0.3

- pom.xml
- src/main/java/com/senzing/api/BuildInfo.java
- src/main/java/com/senzing/api/model/SzConfigResponse.java
- src/main/java/com/senzing/api/model/SzMeta.java
- src/main/java/com/senzing/api/model/SzVersionInfo.java
- src/main/java/com/senzing/api/model/SzVersionResponse.java
- src/main/java/com/senzing/api/services/AdminServices.java
- src/main/java/com/senzing/api/services/ConfigServices.java
- src/test/java/com/senzing/api/services/AbstractServiceTest.java
- src/test/java/com/senzing/api/services/AdminServicesTest.java
- src/test/java/com/senzing/api/services/ConfigServicesTest.java
Addresses Issue 48 and issue 60 to implement the following endpoints:
- /version
- /config/current
- /config/default
Changes include full auto tests of new endpoints
> Added /version, /config/current and /config/default endpoints 

- README.md
Updated the README.md -- forgotten on last pull request
> Updated README.md for version 1.7.2

- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
ISSUE-63
- Improved CHANGELOG.md layout
- Updated Dockerfile for non-root, immutable, and RPM installation
- Improved README.md
- Modified target name in Makefile
> Issue 63.dockter.1

- CHANGELOG.md
- src/test/java/com/senzing/api/services/EntityGraphServicesTest.java
Modified test data so unit tests pass on windows (had to work around lib postal bug in native Senzing API on Windows).
> Fixed Junit Tests for WIndows

- CHANGELOG.md
- Dockerfile
> issue-63  Removed temporary 1.7.3 version

- CHANGELOG.md
Changelog changes that were missing.
> Updated changelog for 1.7.6

- README.md
> issue-100 Update instructions

- CHANGELOG.md
- CONTRIBUTING.md
- Dockerfile
- README.md
- pom.xml
> issue-102 Upgrade to senzing/senzing-base:1.3.0 

- .dockerignore
- CODE_OF_CONDUCT.md
- PULL_REQUEST_TEMPLATE.md
- README.md
> issue-102 Refactor to template

- .github/workflows/cd-3hr-cron-test-deb-build.yml
> fixing the version reference to slack-notification

- .dockerignore
- CHANGELOG.md
- Dockerfile
- README.md
- pom.xml
> Issue 126.dockter.1

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- Dockerfile
Issue number: #132 
update the information captured in when a build fails againt
provides more details about the build failure
> Issue 132.bryan nice

- CHANGELOG.md
Updated CHANGELOG.md for v1.8.0 release
> Updated CHANGELOG.md for v1.8.0 release

- Dockerfile
- pom.xml
Updated pom.xml and Dockerfile for version 1.8.2
> Updated pom.xml and Dockerfile for version 1.8.2

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- .github/workflows/cd-pr-test-debian-build.yml
Issue number: #155 
updated cd pipeline for messages to go to slack channel production-build-failures
> updated config to point to slacke channel production-build-failures

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- .github/workflows/cd-pr-test-debian-build.yml
Issue number: #166 
Fix a breakage in our tool chain
> Issue 166.bryan nice

- Dockerfile
- Makefile
> Update dockerfile to senzing/senzing-base:1.5.0

- CHANGELOG.md
> #170 Prepare for version

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- .github/workflows/cd-pr-test-debian-build.yml
> #173 Fix senzing/base-image/debian:1.0.3 version

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- .github/workflows/cd-pr-test-debian-build.yml
- Dockerfile
- Makefile
> Issue 175.macy.1

- CHANGELOG.md
> #175 upgrade to senzing/senzing-base:1.5.2

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- .github/workflows/cd-pr-test-debian-build.yml
Issue number: #173 
To get the test build for pull requests working again.
> Issue 173.jadair.2

- .github/workflows/cd-pr-test-debian-build.yml
Issue number: #184 
We want a button!
Gives us a button! (hopefully. This needs to go to master before we can test it.)
> Adding in workflow_dispatch so we can get manual action runs!

- Dockerfile
- pom.xml
Fixed version numbers to be 2.1.0 in pom.xml and Dockerfile
> Fixed version numbers to be 2.1.0

- README.md
> #194 Instructions for submodules

- CHANGELOG.md
- NOTICES
- pom.xml
Additional changes to update the pom.xml, CHANGELOG.md and added a new NOTICES file for version 2.3.2.
> Updates to pom.xml and CHANGELOG.md and NOTICES file for version 2.3.2

- README.md
> #221 Update to senzingdata 2.0.0

- .github/workflows/cd-daily-cron-test-debian-build.yml
Installing the proper senzingdata-v2 in the daily test build
> Updating to install senzingdata-v2

- CHANGELOG.md
- Dockerfile
> #227 updated senzing base version

- CHANGELOG.md
- Dockerfile
- Makefile
> Issue 230.dockter.1

- pom.xml
Fixed version number for 2.7.1 release.
> Version 2.7.1 fix for version number

- CHANGELOG.md
- Dockerfile
- README.md
- pom.xml
- src/main/java/com/senzing/api/server/DebugRequestFilter.java
- src/main/java/com/senzing/api/server/SzApiServer.java
- src/main/java/com/senzing/api/server/SzApiServerOption.java
- src/main/java/com/senzing/api/server/SzApiServerOptions.java
- src/main/java/com/senzing/api/services/BulkDataSupport.java
- src/main/java/com/senzing/api/services/BulkDataWebSocket.java
- src/main/java/com/senzing/api/websocket/WebSocketFilter.java
- src/main/java/com/senzing/io/RecordReader.java
- src/main/java/com/senzing/io/TemporaryDataCache.java
- src/main/java/com/senzing/util/LoggingUtilities.java
- src/test/java/com/senzing/api/services/AbstractServiceTest.java
- Improved debug logging with standardized formatting and timestamps.
- Added more debug logging to TemporaryDataCache.
- Renamed enum constant for debug logging from DEBUG to DEBUG_LOGGING.
- Added debug option to SzApiServerOptions for programmatic configuration.
- Added `com.senzing.api.test.debug=true` system property check to run
automated tests with debug logging enabled.
- Modified usage message to include information on `--debug` option.
> Version 2.7.4 -- Improved debug logging

- Dockerfile
Forgotten Dockerfile version change.
> Version 2.8.0 -- Dockerfile changes

- CHANGELOG.md
- pom.xml
- src/main/java/com/senzing/api/model/ModelFactory.java
- src/main/java/com/senzing/api/server/SzApiServer.java
- src/main/java/com/senzing/api/websocket/WebSocketFilter.java
- src/main/java/com/senzing/datagen/DataGenerator.java
- src/main/java/com/senzing/repomgr/RepositoryManager.java
- Updates to latest dependency versions to resolve/avoid security issues.   Specifically resolves CVE-2020-36518 for jackson-databind.
- Added `@SuppressWarnings()` annotation to some files to eliminate specific compile-time warnings.
> Version 2.8.5 Changes

- pom.xml
This should patch the security vulnerability CVE-2020-36518
> Version 2.8.5 patch for CVE-2020-36518

- pom.xml
Did everything but update the version number in the pom.xml....
> Version 2.8.5 version number change in pom.xml

- docker-compose.test.yml
> #272 Fix test docker-compose

- CHANGELOG.md
- Dockerfile
- pom.xml
- Updated `pom.xml` version number
- Updated version number for `senzing-api-server` in `Dockerfile`
- Updated `CHANGELOG.md`
-
> Update versions for 2.8.6 release

- CHANGELOG.md
- Dockerfile
> #280 Add unixodbc

- README.md
Issue number: #278
References to `senzing-data` version 2.0.0 are outdated.
Improves the documentation.
> Updated README.md to reference senzing-data 3.0

- CONTRIBUTING.md
- README.md
> #276 Migrate from master to main

- CHANGELOG.md
- Dockerfile
- pom.xml
> Issue 291.dockter.1

- CHANGELOG.md
Updated version number in `CHANGELOG.md` to `3.3.0`
> Update to version number in CHANGELOG.md

- Dockerfile
> #344 Add SENZING_API_SERVER_BIND_ADDR

- CHANGELOG.md
- Dockerfile
- README.md
- pom.xml
> #317 Prepare for versioned release

- .github/CODEOWNERS
- CHANGELOG.md
- Dockerfile
- pom.xml
- rootfs/app/docker-entrypoint.sh
> #322 Removed CMD from Dockerfile

- README.md
> #346 Add License

- CHANGELOG.md
- Dockerfile
- pom.xml
- rootfs/app/docker-entrypoint.sh
> #361 Revert to 3.3.2

- CHANGELOG.md
- Dockerfile
- pom.xml
> #372 Prepare for versioning

- pom.xml
Updated dependencies to newer versions.
> Updated dependencies to newer versions

- CHANGELOG.md
- Dockerfile
- pom.xml
> Issue 401.ron.0

- CHANGELOG.md
- Dockerfile
- pom.xml
Handled Dependabot updates and prepped new version for release.
> Updates for version 3.4.11

- CHANGELOG.md
Updated 3.4.12 release date in CHANGELOG.md
> Updated 3.4.12 release date in CHANGELOG.md

- README.md
> #428 Update links

- README.md
- docs/development.md
- docs/errors.md
- docs/examples.md
> Issue 435.dockter.1

- CHANGELOG.md
Updated changelog and pushed missing changes.
> Missing changes for version 3.5.1

- pom.xml
Somehow missed the most important part of a new version release -- updating the version number.
> Updated senzing-api-version to 3.5.1

- CHANGELOG.md
- Dockerfile
- pom.xml
- Upgraded "Jackson" libraries to version `2.15.2`
- Upgraded "icu4J" to version `73.1`
- Upgraded "slf4j" to version `2.0.7`
- Upgraded various maven plugin dependencies for building.
> Version 3.5.2 Release

- .project
- CHANGELOG.md
- Dockerfile
- pom.xml
Update underlying docker images.
Issue number: #1
> github-util: Update FROM version

- pom.xml
Forgotten version number update.
> Updated version number of release in pom.xml

- .github/workflows/docker-push-containers-to-dockerhub.yaml
> #1 Fix github action

- .github/linters/.yaml-lint.yml
- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-app-server-dependabot.yaml
- .github/workflows/add-to-project-app-server.yaml
- .github/workflows/docker-build-container.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
- .github/workflows/lint-workflows.yaml
Issue number: senzing-factory/build-resources#69
> senzing-factory/build-resources#69 add linting

- CHANGELOG.md
- pom.xml
Updated CHANGELOG.md to reflet the change and pom.xml for the dependency.
> Updated sqlite dependency since getGeneratedKey() restored

- .github/renovate.json
> #632 disable dependency dashboard
